-- {"id":201111111,"ver":"1.0.1","libVer":"1.0.0","author":"TechnoJo4","dep":["Madara>=2.2.0"]}

return Require("Madara")("https://woopread.com", {
    id = 201111111,
    name = "WoopRead",
    imageURL = "https://github.com/adiaid/adi-shosetsu/blob/master/icons/WoopRead.png",
    -- defaults values
    chaptersListSelector= "li.wp-manga-chapter.free-chap",
    novelListingURLPath = "novellist",
    shrinkURLNovel = "series",
    searchHasOper = true,

    genres = {
        "Action",
        "Adult",
        "Adventure",
        "Comedy",
        "Dark",
        "Drama",
        "Fantasy",
        "Harem",
        "Historical",
        "Horror",
        "Isekai",
        "Josei",
        "Light Novel",
        "Manhua",
        "Manhwa",
        "Martial Arts",
        "Mature",
        "Mystery",
        "Psychological",
        "Romance",
        "School Life",
        "Seinen",
        "Shoujo",
        "Shounen",
        "Supernatural",
        "Thriller",
        "Tragedy",
        "Virtual Reality",
        "Xuanhuan",
        "Canceled",
        "On Hold",
        ["on-going"] = "Ongoing",
        ["complete"] = "Completed",
        ["slice-of-life"] = "Slice of Life",
    }
})
